import { useState, useEffect, useRef } from "react";
import { marked } from "marked";
import { getFunctions, httpsCallable } from "firebase/functions";
import { onAuthStateChanged } from "firebase/auth";
import {
  addDoc,
  collection,
  deleteDoc,
  doc,
  getDocs,
  increment,
  limit,
  onSnapshot,
  orderBy,
  query,
  serverTimestamp,
  setDoc,
  updateDoc,
  where
} from "firebase/firestore";
import htmlToPdfmake from "html-to-pdfmake";
import pdfMake from "pdfmake/build/pdfmake";
import pdfFontsSource from "../../../assets/pdf/vfs_fonts.js?raw";
import { useLanguage } from "../../../context/LanguageContext";
import { auth, db } from "../../../firebase";
import "./AIAssistant.css";

// Import logo as base64 data URL for PDF generation (works in production)
import nabtaLogo from "../../../assets/images/New Project (1).png";
import arabicNabtaLogo from "../../../assets/images/das.png";
import sidebarLeftIcon from "../../../assets/images/sidebar-left-svgrepo-com (1).svg";
import sidebarRightIcon from "../../../assets/images/sidebar-right-svgrepo-com.svg";

const parseLocalVfs = (source) => {
  try {
    const marker = "this.pdfMake.vfs";
    const markerIndex = source.indexOf(marker);
    if (markerIndex === -1) {
      return null;
    }

    const start = source.indexOf("{", markerIndex);
    const end = source.lastIndexOf("};");
    if (start === -1 || end === -1 || end <= start) {
      return null;
    }

    // vfs files generated by pdfmake can contain trailing commas that break JSON.parse.
    const rawObject = source.slice(start, end + 1);
    const normalized = rawObject.replace(/,\s*([}\]])/g, "$1");
    return JSON.parse(normalized);
  } catch (error) {
    console.error("Failed to parse local vfs fonts:", error);
    return null;
  }
};

const localVfs = parseLocalVfs(pdfFontsSource);
const bundledVfs = pdfMake?.vfs || {};
const activeVfs = localVfs || bundledVfs;
const hasCairoFonts =
  !!activeVfs?.["Cairo-Regular.ttf"] &&
  !!activeVfs?.["Cairo-Bold.ttf"];
const hasRobotoFonts =
  !!activeVfs?.["Roboto-Regular.ttf"] &&
  !!activeVfs?.["Roboto-Medium.ttf"] &&
  !!activeVfs?.["Roboto-Italic.ttf"] &&
  !!activeVfs?.["Roboto-MediumItalic.ttf"];

if (localVfs) {
  pdfMake.vfs = localVfs;
} else if (Object.keys(bundledVfs).length > 0) {
  pdfMake.vfs = bundledVfs;
}

pdfMake.fonts = {
  ...(hasRobotoFonts
    ? {
        Roboto: {
          normal: "Roboto-Regular.ttf",
          bold: "Roboto-Medium.ttf",
          italics: "Roboto-Italic.ttf",
          bolditalics: "Roboto-MediumItalic.ttf"
        }
      }
    : {}),
  ...(hasCairoFonts
    ? {
        Cairo: {
          normal: "Cairo-Regular.ttf",
          bold: "Cairo-Bold.ttf",
          italics: "Cairo-Regular.ttf",
          bolditalics: "Cairo-Bold.ttf"
        }
      }
    : {})
};

marked.setOptions({ breaks: true });

const ARABIC_TEXT_REGEX = /[\u0600-\u06FF\u0750-\u077F\u08A0-\u08FF\uFB50-\uFDFF\uFE70-\uFEFC]/;
const DIRECTIONAL_MARKS_REGEX = /[\u200E\u200F\u202A-\u202E\u2066-\u2069]/g;
const PRIVATE_USE_GLYPHS_REGEX = /[\uE000-\uF8FF\u{F0000}-\u{FFFFD}\u{100000}-\u{10FFFD}]/gu;
const WORD_CHARACTER_REGEX = /[\u0600-\u06FFA-Za-z0-9]/;
const NO_SPACE_BEFORE_REGEX = /^[,.;:!?%،؛)\]}»]/;
const NO_SPACE_AFTER_REGEX = /[([{«]$/;
const RTL_GROUP_OPENERS = {
  "(": ")",
  "[": "]",
  "{": "}",
  "«": "»"
};

const PDF_MARKDOWN_REPLACEMENTS = {
  ar: {
    immediateActions: "إجراءات فورية",
    pruning: "تقليم",
    recommendedTreatment: "العلاج الموصى به",
    treatmentSchedule: "الجدول الزمني",
    protectionMeasures: "إجراءات الحماية",
    environmentalFactors: "العوامل البيئية",
    ventilation: "التهوية",
    properSpacing: "التباعد المناسب",
    irrigationManagement: "إدارة الري",
    fertilizationStrategy: "استراتيجية التسميد",
    sanitationPractices: "ممارسات النظافة",
    monitoringPlan: "خطة المتابعة",
    diseaseSpread: "انتشار المرض"
  },
  en: {
    immediateActions: "Immediate Actions",
    pruning: "Pruning",
    recommendedTreatment: "Recommended Treatment",
    treatmentSchedule: "Treatment Schedule",
    protectionMeasures: "Protection Measures",
    environmentalFactors: "Environmental Factors",
    ventilation: "Ventilation",
    properSpacing: "Proper Spacing",
    irrigationManagement: "Irrigation Management",
    fertilizationStrategy: "Fertilization Strategy",
    sanitationPractices: "Sanitation Practices",
    monitoringPlan: "Monitoring Plan",
    diseaseSpread: "Disease Spread"
  }
};

function detectArabic(value = "") {
  return ARABIC_TEXT_REGEX.test(String(value));
}

function escapeRegExp(value = "") {
  return String(value).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function highlightHtmlMatches(html, query, options = {}) {
  const normalizedQuery = String(query ?? "").trim();
  if (!normalizedQuery || typeof document === "undefined") {
    return html;
  }

  const { activeIndex = -1, counterRef } = options;

  const regex = new RegExp(`(${escapeRegExp(normalizedQuery)})`, "gi");
  const container = document.createElement("div");
  container.innerHTML = html;

  const highlightTextNode = (textNode) => {
    const sourceText = textNode.nodeValue || "";
    if (!sourceText.trim()) {
      return;
    }

    if (!regex.test(sourceText)) {
      regex.lastIndex = 0;
      return;
    }

    regex.lastIndex = 0;
    const fragment = document.createDocumentFragment();
    let lastIndex = 0;

    sourceText.replace(regex, (match, _group, offset) => {
      if (offset > lastIndex) {
        fragment.appendChild(document.createTextNode(sourceText.slice(lastIndex, offset)));
      }

      const markIndex = counterRef ? counterRef.value : -1;
      if (counterRef) {
        counterRef.value += 1;
      }

      const mark = document.createElement("mark");
      mark.className = markIndex === activeIndex
        ? "chat-search-highlight chat-search-highlight--active"
        : "chat-search-highlight";
      if (markIndex >= 0) {
        mark.setAttribute("data-search-index", String(markIndex));
      }
      mark.textContent = match;
      fragment.appendChild(mark);
      lastIndex = offset + match.length;

      return match;
    });

    if (lastIndex < sourceText.length) {
      fragment.appendChild(document.createTextNode(sourceText.slice(lastIndex)));
    }

    if (textNode.parentNode) {
      textNode.parentNode.replaceChild(fragment, textNode);
    }
  };

  const walkNodes = (node) => {
    if (!node) {
      return;
    }

    if (node.nodeType === 3) {
      highlightTextNode(node);
      return;
    }

    if (node.nodeType !== 1) {
      return;
    }

    const tagName = node.tagName?.toLowerCase();
    if (tagName === "script" || tagName === "style" || tagName === "mark") {
      return;
    }

    Array.from(node.childNodes).forEach((childNode) => {
      walkNodes(childNode);
    });
  };

  walkNodes(container);
  return container.innerHTML;
}

function getPdfFontPair(isArabicDocument) {
  const preferredFont = isArabicDocument
    ? hasCairoFonts
      ? "Cairo"
      : hasRobotoFonts
        ? "Roboto"
        : undefined
    : hasRobotoFonts
      ? "Roboto"
      : hasCairoFonts
        ? "Cairo"
        : undefined;

  const fallbackFont = preferredFont === "Roboto"
    ? hasCairoFonts
      ? "Cairo"
      : undefined
    : hasRobotoFonts
      ? "Roboto"
      : undefined;

  return { preferredFont, fallbackFont };
}

function shouldInsertFragmentSpace(previousText, nextText) {
  if (!previousText || !nextText) {
    return false;
  }

  if (/\s$/.test(previousText) || /^\s/.test(nextText)) {
    return false;
  }

  if (NO_SPACE_AFTER_REGEX.test(previousText) || NO_SPACE_BEFORE_REGEX.test(nextText)) {
    return false;
  }

  return WORD_CHARACTER_REGEX.test(previousText.slice(-1)) && WORD_CHARACTER_REGEX.test(nextText[0]);
}

function joinTextFragments(fragments, separator = "") {
  return fragments.reduce((combinedText, fragment) => {
    const textFragment = String(fragment ?? "");

    if (!textFragment) {
      return combinedText;
    }

    if (!combinedText) {
      return textFragment;
    }

    if (separator) {
      return `${combinedText}${separator}${textFragment}`;
    }

    return shouldInsertFragmentSpace(combinedText, textFragment)
      ? `${combinedText} ${textFragment}`
      : `${combinedText}${textFragment}`;
  }, "");
}

function prependInlineFragmentText(fragment, prefix) {
  if (!prefix) {
    return fragment;
  }

  if (typeof fragment === "string") {
    return `${prefix}${fragment}`;
  }

  if (fragment && typeof fragment === "object") {
    if (typeof fragment.text === "string") {
      return {
        ...fragment,
        text: `${prefix}${fragment.text}`
      };
    }

    if (Array.isArray(fragment.text) && fragment.text.length > 0) {
      const [firstItem, ...restItems] = fragment.text;

      return {
        ...fragment,
        text: [prependInlineFragmentText(firstItem, prefix), ...restItems]
      };
    }
  }

  return fragment;
}

function getInlineStyleProps(fragment) {
  if (!fragment || typeof fragment !== "object") {
    return {};
  }

  const { text: _text, ...styleProps } = fragment;
  return styleProps;
}

function flattenInlineFragments(value, inheritedProps = {}) {
  if (value === null || value === undefined || value === "") {
    return [];
  }

  if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") {
    return [{ text: String(value), props: inheritedProps }];
  }

  if (Array.isArray(value)) {
    return value.flatMap((entry) => flattenInlineFragments(entry, inheritedProps));
  }

  if (typeof value === "object") {
    if (Object.prototype.hasOwnProperty.call(value, "text")) {
      return flattenInlineFragments(value.text, {
        ...inheritedProps,
        ...getInlineStyleProps(value)
      });
    }

    const fallbackText = extractText(value);
    return fallbackText ? [{ text: fallbackText, props: inheritedProps }] : [];
  }

  return [{ text: String(value), props: inheritedProps }];
}

function tokenizeSegmentPreserveGroups(text) {
  const tokens = [];
  let currentToken = "";
  const expectedClosers = [];

  const pushCurrentToken = () => {
    const trimmedToken = currentToken.trim();
    if (trimmedToken) {
      tokens.push(trimmedToken);
    }

    currentToken = "";
  };

  for (const character of String(text ?? "")) {
    if (!expectedClosers.length && /\s/.test(character)) {
      pushCurrentToken();
      continue;
    }

    currentToken += character;

    if (RTL_GROUP_OPENERS[character]) {
      expectedClosers.push(RTL_GROUP_OPENERS[character]);
      continue;
    }

    if (expectedClosers.length && character === expectedClosers[expectedClosers.length - 1]) {
      expectedClosers.pop();
    }
  }

  pushCurrentToken();

  return tokens;
}

function isLatinLikeToken(tokenText) {
  const normalizedToken = String(tokenText ?? "").replace(/^[("'[\u00AB]+|[)"'\].,:;!?%\u00BB]+$/g, "");
  return /[A-Za-z]/.test(normalizedToken) && !detectArabic(normalizedToken);
}

function mergeConsecutiveLatinTokens(tokens) {
  return tokens.reduce((mergedTokens, token) => {
    const previousToken = mergedTokens[mergedTokens.length - 1];
    const sameStyle =
      previousToken &&
      JSON.stringify(previousToken.props || {}) === JSON.stringify(token.props || {});

    if (previousToken && sameStyle && isLatinLikeToken(previousToken.text) && isLatinLikeToken(token.text)) {
      previousToken.text = `${previousToken.text} ${token.text}`;
      return mergedTokens;
    }

    mergedTokens.push({ ...token });
    return mergedTokens;
  }, []);
}

function buildInlineFragmentFromToken(token, isLastToken, options) {
  const normalizedTokenText = normalizeArabicMarkerToken(token.text);
  const fragmentText = isLastToken ? normalizedTokenText : `${normalizedTokenText} `;
  const fragmentFont = selectPdfFont(
    normalizedTokenText,
    options.preferredFont,
    options.fallbackFont
  );

  return {
    ...(token.props || {}),
    text: fragmentText,
    ...(!(token.props || {}).font && fragmentFont ? { font: fragmentFont } : {})
  };
}

function reorderArabicInlineFragments(textItems, options) {
  const flattenedFragments = flattenInlineFragments(textItems);
  const lines = [[]];

  flattenedFragments.forEach((fragment) => {
    const parts = String(fragment.text ?? "").split("\n");

    parts.forEach((part, partIndex) => {
      const tokens = tokenizeSegmentPreserveGroups(part).map((tokenText) => ({
        text: tokenText,
        props: fragment.props || {}
      }));

      if (tokens.length) {
        lines[lines.length - 1].push(...tokens);
      }

      if (partIndex < parts.length - 1) {
        lines.push([]);
      }
    });
  });

  return lines.flatMap((lineTokens, lineIndex) => {
    const hasArabicLine = detectArabic(joinTextFragments(lineTokens.map((token) => token.text), " "));
    const orderedTokens = hasArabicLine
      ? mergeConsecutiveLatinTokens(lineTokens).reverse()
      : lineTokens;

    const lineFragments = orderedTokens.map((token, tokenIndex) =>
      buildInlineFragmentFromToken(token, tokenIndex === orderedTokens.length - 1, options)
    );

    if (lineIndex === lines.length - 1) {
      return lineFragments;
    }

    if (!lineFragments.length) {
      return [{ text: "\n" }];
    }

    const lastFragment = lineFragments[lineFragments.length - 1];
    lineFragments[lineFragments.length - 1] = {
      ...lastFragment,
      text: `${lastFragment.text}\n`
    };

    return lineFragments;
  });
}

function normalizeInlineArray(textItems, options) {
  const normalizedFragments = textItems.flatMap((item) => {
    if (item === null || item === undefined || item === "") {
      return [];
    }

    if (typeof item === "string") {
      return [shapePdfText(item, options.isArabicDocument)];
    }

    if (Array.isArray(item)) {
      return normalizeInlineArray(item, options);
    }

    if (typeof item === "object") {
      if (Object.prototype.hasOwnProperty.call(item, "text")) {
        const normalizedItem = { ...item };
        normalizedItem.text = normalizeInlineText(item.text, options);

        const inlineFont = selectPdfFont(
          normalizedItem.text,
          options.preferredFont,
          options.fallbackFont
        );

        if (inlineFont && !normalizedItem.font) {
          normalizedItem.font = inlineFont;
        }

        return [normalizedItem];
      }

      const fallbackText = shapePdfText(extractText(item), options.isArabicDocument);
      if (!fallbackText) {
        return [];
      }

      return [
        {
          text: fallbackText,
          font: selectPdfFont(fallbackText, options.preferredFont, options.fallbackFont)
        }
      ];
    }

    return [shapePdfText(String(item), options.isArabicDocument)];
  }).filter(Boolean);

  return normalizedFragments.reduce((fragments, fragment) => {
    const previousFragment = fragments[fragments.length - 1];
    const previousText = previousFragment ? extractText(previousFragment) : "";
    const currentText = extractText(fragment);

    if (shouldInsertFragmentSpace(previousText, currentText)) {
      fragments.push(prependInlineFragmentText(fragment, " "));
      return fragments;
    }

    fragments.push(fragment);
    return fragments;
  }, []);
}

function extractText(value) {
  if (value === null || value === undefined) {
    return "";
  }

  if (typeof value === "string") {
    return value;
  }

  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }

  if (Array.isArray(value)) {
    return joinTextFragments(value.map((item) => extractText(item)));
  }

  if (typeof value === "object") {
    if (Object.prototype.hasOwnProperty.call(value, "text")) {
      return extractText(value.text);
    }

    if (Array.isArray(value.stack)) {
      return joinTextFragments(value.stack.map((item) => extractText(item)), " ");
    }

    if (Array.isArray(value.columns)) {
      return joinTextFragments(value.columns.map((item) => extractText(item)), " ");
    }

    if (Array.isArray(value.ul)) {
      return joinTextFragments(value.ul.map((item) => extractText(item)), " ");
    }

    if (Array.isArray(value.ol)) {
      return joinTextFragments(value.ol.map((item) => extractText(item)), " ");
    }
  }

  return "";
}

function selectPdfFont(value, preferredFont, fallbackFont) {
  const rawText = extractText(value);

  if (detectArabic(rawText)) {
    return hasCairoFonts ? "Cairo" : preferredFont || fallbackFont;
  }

  return hasRobotoFonts ? "Roboto" : preferredFont || fallbackFont;
}

function normalizeArabicMarkerToken(token) {
  return String(token ?? "").replace(/^(\d+)\.$/, ".$1");
}

function reorderArabicLine(value) {
  const normalizedLine = String(value ?? "")
    .replace(/\*\*\s*:\s*\*\*/g, ":")
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/(^|\s)(\d+)\s*\.\s+/g, "$1$2. ")
    .replace(/\s+/g, " ")
    .trim();

  if (!normalizedLine || !detectArabic(normalizedLine)) {
    return normalizedLine;
  }

  return mergeConsecutiveLatinTokens(
    tokenizeSegmentPreserveGroups(normalizedLine).map((tokenText) => ({ text: tokenText, props: {} }))
  )
    .reverse()
    .map((token) => normalizeArabicMarkerToken(token.text))
    .join(" ");
}

function reorderArabicTextBlock(value) {
  return String(value ?? "")
    .split("\n")
    .map((line) => reorderArabicLine(line))
    .join("\n");
}

function shapePdfText(value, isArabicDocument) {
  const normalizedText = String(value ?? "")
    .replace(/\u00A0/g, " ")
    .replace(DIRECTIONAL_MARKS_REGEX, "")
    .replace(PRIVATE_USE_GLYPHS_REGEX, "")
    .replace(/[ \t]+\n/g, "\n")
    .replace(/\n{3,}/g, "\n\n");

  if (!normalizedText.trim()) {
    return "";
  }

  if (!isArabicDocument || !detectArabic(normalizedText)) {
    return normalizedText;
  }

  return reorderArabicTextBlock(normalizedText);
}

function cleanMarkdown(markdown, pdfLanguage) {
  const replacementLabels = PDF_MARKDOWN_REPLACEMENTS[pdfLanguage] || PDF_MARKDOWN_REPLACEMENTS.en;

  const cleanedMarkdown = String(markdown ?? "")
    .replace(/\r\n/g, "\n")
    .replace(/\u00A0/g, " ")
    .replace(/🌿/gu, "")
    .replace(/🌱/gu, "")
    .replace(/📊/gu, "")
    .replace(/📈/gu, "")
    .replace(/📋/gu, "")
    .replace(/📌/gu, "")
    .replace(/⚠️?/gu, "")
    .replace(/🧠/gu, "")
    .replace(/🛑/gu, replacementLabels.immediateActions)
    .replace(/✂️?/gu, replacementLabels.pruning)
    .replace(/🧪/gu, replacementLabels.recommendedTreatment)
    .replace(/📅/gu, replacementLabels.treatmentSchedule)
    .replace(/🛡️?/gu, replacementLabels.protectionMeasures)
    .replace(/🌦️?/gu, replacementLabels.environmentalFactors)
    .replace(/🌬️?/gu, replacementLabels.ventilation)
    .replace(/📏/gu, replacementLabels.properSpacing)
    .replace(/💦/gu, replacementLabels.irrigationManagement)
    .replace(/🌾/gu, replacementLabels.fertilizationStrategy)
    .replace(/🧼/gu, replacementLabels.sanitationPractices)
    .replace(/🧑‍🌾/gu, replacementLabels.monitoringPlan)
    .replace(/🔄/gu, replacementLabels.diseaseSpread)
    .replace(/1️⃣/gu, "1.")
    .replace(/2️⃣/gu, "2.")
    .replace(/3️⃣/gu, "3.")
    .replace(/4️⃣/gu, "4.")
    .replace(/5️⃣/gu, "5.")
    .replace(/6️⃣/gu, "6.")
    .replace(/7️⃣/gu, "7.")
    .replace(/8️⃣/gu, "8.")
    .replace(/9️⃣/gu, "9.")
    .replace(/🔟/gu, "10.")
    .replace(/\uFE0F/g, "")
    .replace(/\uFEFF/g, "")
    .replace(/\u20E3/g, "")
    .replace(/[\u2028\u2029]/g, "")
    .replace(/[\u200B\u200C\u200D]/g, "")
    .replace(PRIVATE_USE_GLYPHS_REGEX, "")
    .replace(/[ \t]+\n/g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .replace(/[\p{Emoji_Presentation}\p{Extended_Pictographic}]/gu, "");

  if (pdfLanguage === "en") {
    return cleanedMarkdown
      .replace(/\*\*\s+Soil/g, "**Soil")
      .replace(/\*\*\s+Watering:/g, "**Watering")
      .replace(/\*\*\s+Fertilization/g, "**Fertilization")
      .trim();
  }

  return cleanedMarkdown
    .replace(/\*\*\s*([^*][\s\S]*?)\s*\*\*/g, (match, innerText) => {
      const normalizedInnerText = String(innerText ?? "").trim();
      return normalizedInnerText ? `**${normalizedInnerText}**` : match;
    })
    .replace(/\*\*\s*:\s*\*\*/g, ":")
    .replace(/\*\*\s+([^\s*])/g, "**$1")
    .replace(/(\*\*[^*\n]+:\*\*)(?=\S)/g, "$1 ")
    .replace(/(^|\n)\s*(\d+)\s*\.\s+/g, "$1$2. ")
    .replace(/([^\n])(\n[-*]\s)/g, "$1\n$2")
    .replace(/([^\n])(\n\d+\.\s)/g, "$1\n$2")
    .trim();
}

function normalizeInlineText(textValue, options) {
  if (typeof textValue === "string") {
    return shapePdfText(textValue, options.isArabicDocument);
  }

  if (Array.isArray(textValue)) {
    if (options.isArabicDocument && detectArabic(extractText(textValue))) {
      return reorderArabicInlineFragments(textValue, options);
    }

    return normalizeInlineArray(textValue, options);
  }

  if (textValue && typeof textValue === "object") {
    return shapePdfText(extractText(textValue), options.isArabicDocument);
  }

  return shapePdfText(String(textValue ?? ""), options.isArabicDocument);
}

function applyPdfNodeStyles(node, options) {
  const nodeText = extractText(node.text ?? node.stack ?? node.columns ?? node.table);
  const resolvedFont = selectPdfFont(nodeText, options.preferredFont, options.fallbackFont);

  if (resolvedFont && !node.font) {
    node.font = resolvedFont;
  }

  if (options.isArabicDocument) {
    node.alignment = node.alignment || "right";
    node.preserveLeadingSpaces = true;
  } else if (!node.alignment && (node.text || node.stack || node.columns)) {
    node.alignment = "left";
  }

  return node;
}

function extractListItemText(item) {
  if (typeof item === "string") {
    return item;
  }

  if (Array.isArray(item)) {
    return joinTextFragments(item.map((entry) => extractListItemText(entry)), " ").trim();
  }

  if (!item || typeof item !== "object") {
    return String(item ?? "");
  }

  if (Object.prototype.hasOwnProperty.call(item, "text")) {
    return extractText(item.text).trim();
  }

  if (Array.isArray(item.stack)) {
    return joinTextFragments(
      item.stack
        .filter((entry) => !(entry && typeof entry === "object" && (entry.ul || entry.ol)))
        .map((entry) => extractText(entry)),
      " "
    ).trim();
  }

  return extractText(item).trim();
}

function buildListNodes(items, options, ordered = false, level = 0) {
  if (!Array.isArray(items)) {
    return [];
  }

  return items.flatMap((item, index) => {
    const itemText = shapePdfText(extractListItemText(item), options.isArabicDocument);
    const markerText = ordered
      ? options.isArabicDocument
        ? `.${index + 1}`
        : `${index + 1}.`
      : "\u2022";
    const markerColumn = {
      width: 16,
      text: markerText,
      alignment: "center",
      font: selectPdfFont(markerText, options.preferredFont, options.fallbackFont) || options.preferredFont
    };

    const textColumn = applyPdfNodeStyles(
      {
        width: "*",
        text: itemText
      },
      options
    );

    const listRow = itemText
      ? {
          columns: options.isArabicDocument
            ? [textColumn, markerColumn]
            : [markerColumn, textColumn],
          columnGap: 6,
          margin: options.isArabicDocument
            ? [0, 4, level * 14, 4]
            : [level * 14, 4, 0, 4]
        }
      : null;

    const nestedListNodes = [];
    if (item && typeof item === "object" && Array.isArray(item.stack)) {
      item.stack.forEach((stackItem) => {
        if (stackItem?.ul || stackItem?.ol) {
          nestedListNodes.push(...fixBulletNodes([stackItem], options, level + 1));
        }
      });
    }

    return listRow ? [listRow, ...nestedListNodes] : nestedListNodes;
  });
}

function normalizePdfNode(node, options, level = 0) {
  if (node === null || node === undefined) {
    return null;
  }

  if (Array.isArray(node)) {
    return { stack: fixBulletNodes(node, options, level) };
  }

  if (typeof node === "string") {
    const text = shapePdfText(node, options.isArabicDocument);
    if (!text) {
      return null;
    }

    return applyPdfNodeStyles({ text }, options);
  }

  if (typeof node !== "object") {
    const text = shapePdfText(String(node), options.isArabicDocument);
    return text ? applyPdfNodeStyles({ text }, options) : null;
  }

  if (node.ul) {
    return { stack: buildListNodes(node.ul, options, false, level) };
  }

  if (node.ol) {
    return { stack: buildListNodes(node.ol, options, true, level) };
  }

  const normalizedNode = { ...node };

  if (Object.prototype.hasOwnProperty.call(node, "text")) {
    normalizedNode.text = normalizeInlineText(node.text, options);
  }

  if (Array.isArray(node.stack)) {
    normalizedNode.stack = fixBulletNodes(node.stack, options, level);
  }

  if (Array.isArray(node.columns)) {
    normalizedNode.columns = node.columns
      .map((column) => normalizePdfNode(column, options, level + 1))
      .filter(Boolean)
      .map((column) => (Array.isArray(column) ? { stack: column } : column));
  }

  if (node.table?.body) {
    normalizedNode.table = {
      ...node.table,
      body: node.table.body.map((row) =>
        row.map((cell) => {
          const normalizedCell = normalizePdfNode(cell, options, level + 1);
          if (Array.isArray(normalizedCell)) {
            return { stack: normalizedCell };
          }

          return normalizedCell || "";
        })
      )
    };
  }

  return applyPdfNodeStyles(normalizedNode, options);
}

function fixBulletNodes(nodes, options, level = 0) {
  const normalizedNodes = Array.isArray(nodes) ? nodes : [nodes];

  return normalizedNodes.flatMap((node) => {
    if (node && typeof node === "object" && node.ul) {
      return buildListNodes(node.ul, options, false, level);
    }

    if (node && typeof node === "object" && node.ol) {
      return buildListNodes(node.ol, options, true, level);
    }

    const normalizedNode = normalizePdfNode(node, options, level);

    if (!normalizedNode) {
      return [];
    }

    return Array.isArray(normalizedNode) ? normalizedNode : [normalizedNode];
  });
}

async function toBase64(url) {
  try {
    const response = await fetch(url, { mode: "cors" });
    const blob = await response.blob();

    return await new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch {
    return new Promise((resolve) => {
      const image = new Image();
      image.crossOrigin = "anonymous";

      image.onload = () => {
        const canvas = document.createElement("canvas");
        canvas.width = image.width;
        canvas.height = image.height;

        const context = canvas.getContext("2d");
        context.drawImage(image, 0, 0);
        resolve(canvas.toDataURL("image/png"));
      };

      image.onerror = () => resolve("");
      image.src = url;
    });
  }
}

function buildPdfDefinition({
  pdfText,
  pdfIsArabic,
  preferredFont,
  fallbackFont,
  logoBase64,
  generatedAt,
  contentNodes
}) {
  const titleFont = selectPdfFont(pdfText.pdfTitle, preferredFont, fallbackFont) || preferredFont;
  const metaText = `${pdfText.generatedOn} ${generatedAt}`;
  const metaFont = selectPdfFont(metaText, preferredFont, fallbackFont) || preferredFont;

  const titleStackColumn = {
    width: "*",
    stack: [
      {
        text: shapePdfText(pdfText.pdfTitle, pdfIsArabic),
        font: titleFont,
        fontSize: 22,
        bold: true,
        alignment: logoBase64 ? "center" : "left"
      },
      {
        margin: [0, 8, 0, 8],
        canvas: [
          {
            type: "rect",
            x: pdfIsArabic ? 0 : -140,
            y: -20,
            w: 500,
            h: 6,
            color: "#DC2626"
          }
        ]
      },
      {
        text: shapePdfText(metaText, pdfIsArabic),
        font: metaFont,
        fontSize: 10,
        color: "gray",
        margin: [0, 5, 0, 5],
        alignment: logoBase64 ? "center" : "left"
      }
    ]
  };

  const logoColumn = logoBase64
    ? {
        image: logoBase64,
        width: 130,
        ...(pdfIsArabic ? { relativePosition: { x: -140, y: 0 } } : {})
      }
    : null;

  return {
    pageSize: "A4",
    pageMargins: [40, 110, 40, 60],
    defaultStyle: {
      ...(preferredFont ? { font: preferredFont } : {}),
      fontSize: 11,
      lineHeight: 1.6,
      alignment: pdfIsArabic ? "right" : "left",
      preserveLeadingSpaces: true
    },
    header: {
      margin: [40, 24, 40, 12],
      columns: pdfIsArabic
        ? [titleStackColumn, ...(logoColumn ? [logoColumn] : [])]
        : [...(logoColumn ? [logoColumn] : []), titleStackColumn],
      columnGap: 16
    },
    footer(currentPage, pageCount) {
      const pageText = pdfText.pageOf
        .replace("{{current}}", String(currentPage))
        .replace("{{total}}", String(pageCount));

      return {
        margin: [40, 8, 40, 20],
        columns: pdfIsArabic
          ? [
              {
                text: shapePdfText(pageText, true),
                alignment: "left",
                fontSize: 8,
                color: "#6B7280",
                font: selectPdfFont(pageText, preferredFont, fallbackFont) || preferredFont
              },
              {
                text: shapePdfText(pdfText.assistantName, true),
                alignment: "right",
                fontSize: 8,
                color: "#6B7280",
                font: selectPdfFont(pdfText.assistantName, preferredFont, fallbackFont) || preferredFont
              }
            ]
          : [
              {
                text: pdfText.assistantName,
                alignment: "left",
                fontSize: 8,
                color: "#6B7280",
                font: selectPdfFont(pdfText.assistantName, preferredFont, fallbackFont) || preferredFont
              },
              {
                text: pageText,
                alignment: "right",
                fontSize: 8,
                color: "#6B7280",
                font: selectPdfFont(pageText, preferredFont, fallbackFont) || preferredFont
              }
            ]
      };
    },
    content: [
      {
        stack: contentNodes
      }
    ],
    styles: {
      h1: {
        fontSize: 20,
        bold: true,
        margin: [0, 16, 0, 8],
        alignment: pdfIsArabic ? "right" : "left"
      },
      h2: {
        fontSize: 16,
        bold: true,
        margin: [0, 12, 0, 6],
        alignment: pdfIsArabic ? "right" : "left"
      },
      h3: {
        fontSize: 14,
        bold: true,
        margin: [0, 10, 0, 5],
        alignment: pdfIsArabic ? "right" : "left"
      }
    }
  };
}

const text = {
  en: {
    welcome: "Welcome to Nabta AI Assistant! 🌿 I am your personal botanist. How can I help your garden grow today? I can help with plant identification, care tips, or diagnosing diseases.",
    chats: "AI Conversations",
    newChatSidebar: "New chat",
    untitledChat: "New chat",
    noChats: "No chats yet",
    loadingChats: "Loading chats...",
    chatsLoadError: "Could not load chats",
    collapseChats: "Collapse chats",
    expandChats: "Expand chats",
    deleteChat: "Delete chat",
    deleteChatTitle: "Delete chat?",
    deleteChatConfirm: "Delete this chat permanently?",
    cancelDelete: "Cancel",
    confirmDelete: "Delete",
    menuLabel: "Chat options",
    downloadReport: "Download Professional PDF Report",
    downloading: "Downloading...",
    loading: "Examining roots...",
    placeholder: "Ask about wilting leaves...",
    noResults: "No matching chat messages",
    disclaimer: "Ask a plant 🌿 Nabta AI Assistant can make mistakes. Check important info.",
    pdfTitle: "Nabta AI Smart Plant Report",
    generatedOn: "Generated on:",
    assistantName: "Nabta AI Assistant",
    pageOf: "Page {{current}} of {{total}}"
  },
  ar: {
    welcome: "مرحباً بك في مساعد نبتة الذكي! 🌿 أنا خبيرك النباتي الشخصي. كيف يمكنني مساعدتك في العناية بنباتاتك اليوم؟ أقدر أساعدك في التعرف على النباتات، نصائح العناية، وتشخيص الأمراض.",
    chats: "المحادثات",
    newChatSidebar: "محادثة جديدة",
    untitledChat: "محادثة جديدة",
    noChats: "لا توجد محادثات بعد",
    loadingChats: "جار تحميل المحادثات...",
    chatsLoadError: "تعذر تحميل المحادثات",
    collapseChats: "طي المحادثات",
    expandChats: "فتح المحادثات",
    deleteChat: "حذف المحادثة",
    deleteChatTitle: "حذف المحادثة؟",
    deleteChatConfirm: "هل تريد حذف هذه المحادثة نهائيا؟",
    cancelDelete: "إلغاء",
    confirmDelete: "حذف",
    menuLabel: "خيارات المحادثة",
    downloadReport: "تنزيل تقرير PDF احترافي",
    downloading: "جاري التنزيل...",
    loading: "... فحص الجذور",
    placeholder: "اسأل عن ذبول الأوراق...",
    noResults: "لا توجد رسائل مطابقة للبحث",
    disclaimer: "اسأل نبتة 🌿 قد يخطئ مساعد نبتة الذكي. راجع المعلومات المهمة.",
    pdfTitle: "تقرير نبتة الذكي لصحة النبات",
    generatedOn: "تاريخ الإنشاء:",
    assistantName: "مساعد نبتة الذكي",
    pageOf: "صفحة {{current}} من {{total}}"
  }
};

function getChatTitleFromText(value, fallbackTitle) {
  const normalized = String(value || "").replace(/\s+/g, " ").trim();
  if (!normalized) {
    return fallbackTitle;
  }

  return normalized.length > 44 ? `${normalized.slice(0, 44)}...` : normalized;
}

function getChatPreviewFromText(value) {
  const normalized = String(value || "").replace(/\s+/g, " ").trim();
  if (!normalized) {
    return "";
  }

  return normalized.length > 70 ? `${normalized.slice(0, 70)}...` : normalized;
}

function getSessionTimeValue(session) {
  const rawValue = session?.updatedAt || session?.createdAt || null;
  if (!rawValue) {
    return 0;
  }

  const dateValue = rawValue?.toDate ? rawValue.toDate() : new Date(rawValue);
  const time = dateValue.getTime();
  return Number.isNaN(time) ? 0 : time;
}

export default function AIAssistant({
  pendingReport,
  onReportProcessed,
  newChatTrigger,
  searchQuery = "",
  searchJumpRequest,
  onSearchMatchStatsChange
}) {
  const { language } = useLanguage();
  const t = text[language] || text.en;

  const functions = getFunctions();
  const cohereChat = httpsCallable(functions, "cohereChat");

  const SYSTEM_PREAMBLE = `
  You are Nabta AI Assistant, an expert botanist, horticulturist, and plant pathologist.
  
  YOUR PURPOSE:
  1. Assist users with plant care (watering, light, soil, humidity, fertilization).
  2. Help identify plants based on descriptions.
  3. Diagnose plant diseases and suggest organic or chemical remedies.
  4. Provide gardening tips and best practices.
  
  STRICT DOMAIN RULES:
  - Only answer plant-related questions.
  - Politely refuse other topics.
  
  TONE:
  - Earthy, nurturing, scientific but accessible.
  - Use plant metaphors.
  - Be encouraging.
  `;

  const [messages, setMessages] = useState([]);
  const [chatSessions, setChatSessions] = useState([]);
  const [activeChatId, setActiveChatId] = useState("");
  const [authUser, setAuthUser] = useState(null);
  const [isChatSessionsLoading, setIsChatSessionsLoading] = useState(true);
  const [chatSessionsError, setChatSessionsError] = useState("");
  const [isSessionsCollapsed, setIsSessionsCollapsed] = useState(false);
  const [openSessionMenuId, setOpenSessionMenuId] = useState("");
  const [pendingDeleteChatId, setPendingDeleteChatId] = useState("");
  const creatingChatRef = useRef(false);

  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [isReportLoading, setIsReportLoading] = useState(false);
  const [downloadingId, setDownloadingId] = useState(null);
  const [downloadProgress, setDownloadProgress] = useState(0);
  const [typingMessageId, setTypingMessageId] = useState(null);
  const [typedText, setTypedText] = useState("");
  const [activeRequestLanguage, setActiveRequestLanguage] = useState(null);

  const textareaRef = useRef(null);
  const messagesContainerRef = useRef(null);
  const messagesEndRef = useRef(null);
  const sessionsPanelRef = useRef(null);
  const hasProcessedReportRef = useRef(false);
  const [activeSearchMatchIndex, setActiveSearchMatchIndex] = useState(0);

  const isArabic = detectArabic;
  const normalizedSearchQuery = searchQuery.trim().toLowerCase();
  const languageSidebarIcon = language === "ar" ? sidebarRightIcon : sidebarLeftIcon;
  const visibleMessages = messages.length > 0
    ? messages
    : [
        {
          id: "welcome",
          role: "bot",
          text: t.welcome,
          isArabic: language === "ar"
        }
      ];

  const filteredMessages = normalizedSearchQuery
    ? visibleMessages.filter((msg) => {
        const searchableText = [
          msg.text,
          msg.originalText,
          msg.downloadLabel,
          msg.downloadingLabel
        ]
          .filter(Boolean)
          .join(" ")
          .toLowerCase();

        return searchableText.includes(normalizedSearchQuery);
      })
    : visibleMessages;

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  const generateChatTitleFromMessage = async (messageText) => {
    const raw = String(messageText || "").trim();
    if (!raw) {
      return t.untitledChat;
    }

    try {
      const titlePrompt = language === "ar"
        ? `استخرج عنوان قصير جدا من الرسالة التالية (3 إلى 6 كلمات فقط بدون علامات اقتباس):\n${raw}`
        : `Generate a very short chat title from this message (3 to 6 words, no quotes):\n${raw}`;

      const titleResponse = await cohereChat({
        message: titlePrompt,
        preamble: "You generate concise chat titles only.",
        temperature: 0.2
      });

      const cleanTitle = String(titleResponse?.data?.text || "")
        .replace(/[\n\r]+/g, " ")
        .replace(/^['"`\-\s]+|['"`\-\s]+$/g, "")
        .trim();

      return getChatTitleFromText(cleanTitle || raw, t.untitledChat);
    } catch {
      return getChatTitleFromText(raw, t.untitledChat);
    }
  };

  const isChatSessionEmpty = async (chatId) => {
    if (!authUser?.uid || !chatId) {
      return false;
    }

    const currentSession = chatSessions.find((session) => session.id === chatId);
    if (typeof currentSession?.messageCount === "number") {
      return currentSession.messageCount <= 0;
    }

    const messagesRef = collection(db, "chatAi", chatId, "messages");
    const snap = await getDocs(query(messagesRef, limit(1)));
    return snap.empty;
  };

  const deleteChatSession = async (chatId) => {
    if (!authUser?.uid || !chatId) {
      return false;
    }

    try {
      const messagesRef = collection(db, "chatAi", chatId, "messages");
      const messagesSnap = await getDocs(messagesRef);
      const deletePromises = messagesSnap.docs.map((messageDoc) => deleteDoc(messageDoc.ref));
      await Promise.all(deletePromises);
      await deleteDoc(doc(db, "chatAi", chatId));

      if (activeChatId === chatId) {
        setActiveChatId("");
        setMessages([]);
      }

      setOpenSessionMenuId("");
      setPendingDeleteChatId("");
      return true;
    } catch (error) {
      console.error("Failed to delete chat:", error);
      return false;
    }
  };

  const createChatSessionDocument = async () => {
    if (!authUser?.uid || creatingChatRef.current) {
      return null;
    }

    creatingChatRef.current = true;
    try {
      const chatRef = doc(collection(db, "chatAi"));
      await setDoc(chatRef, {
        ownerId: authUser.uid,
        title: t.untitledChat,
        preview: "",
        messageCount: 0,
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      });
      setActiveChatId(chatRef.id);
      return chatRef.id;
    } catch (error) {
      console.error("Failed to create chatAi session:", error);
      return null;
    } finally {
      creatingChatRef.current = false;
    }
  };

  const startNewChatDraft = async () => {
    if (activeChatId) {
      const shouldDeleteCurrent = await isChatSessionEmpty(activeChatId);
      if (shouldDeleteCurrent) {
        await deleteChatSession(activeChatId);
      }
    }

    setActiveChatId("");
    setMessages([]);
    setInput("");
    setOpenSessionMenuId("");
  };

  const handleConfirmDeleteChat = async () => {
    if (!pendingDeleteChatId) {
      return;
    }

    await deleteChatSession(pendingDeleteChatId);
  };

  const saveMessageToChat = async (chatId, message, options = {}) => {
    if (!authUser?.uid || !chatId || !message || message.isDownloadLink) {
      return;
    }

    const messagesRef = collection(db, "chatAi", chatId, "messages");
    await addDoc(messagesRef, {
      role: message.role,
      text: message.text,
      isArabic: !!message.isArabic,
      isReport: !!message.isReport,
      createdAt: serverTimestamp()
    });

    const preview = getChatPreviewFromText(message.text);
    const chatRef = doc(db, "chatAi", chatId);
    const patch = {
      preview,
      messageCount: increment(1),
      updatedAt: serverTimestamp()
    };

    if (options.useMessageAsTitle) {
      patch.title = await generateChatTitleFromMessage(message.text);
    }

    await updateDoc(chatRef, patch);
  };

  const downloadPdf = async (markdownText, reportLanguage) => {
    const pdfLanguage = reportLanguage || (detectArabic(markdownText) ? "ar" : "en");
    const pdfText = text[pdfLanguage] || text.en;
    const pdfIsArabic = pdfLanguage === "ar";
    const { preferredFont, fallbackFont } = getPdfFontPair(pdfIsArabic);
    const cleanedMarkdown = cleanMarkdown(markdownText, pdfLanguage);
    const html = marked.parse(cleanedMarkdown);
    const convertedNodes = pdfIsArabic
      ? htmlToPdfmake(html, {
          defaultStyles: {
            p: { margin: [0, 0, 0, 10] },
            ul: { margin: [0, 4, 0, 10] },
            ol: { margin: [0, 4, 0, 10] },
            li: { margin: [0, 2, 0, 2] },
            h1: { margin: [0, 16, 0, 8], bold: true, fontSize: 20 },
            h2: { margin: [0, 12, 0, 6], bold: true, fontSize: 16 },
            h3: { margin: [0, 10, 0, 5], bold: true, fontSize: 14 }
          }
        })
      : htmlToPdfmake(html);

    const normalizationOptions = {
      isArabicDocument: pdfIsArabic,
      preferredFont,
      fallbackFont
    };

    const contentNodes = pdfIsArabic
      ? fixBulletNodes(
          Array.isArray(convertedNodes) ? convertedNodes : [convertedNodes],
          normalizationOptions
        )
      : (Array.isArray(convertedNodes) ? convertedNodes : [convertedNodes]);

    const selectedLogo = pdfIsArabic ? arabicNabtaLogo : nabtaLogo;
    const logoBase64 = await toBase64(selectedLogo);
    const generatedAt = new Intl.DateTimeFormat(pdfIsArabic ? "ar-EG" : "en-US", {
      dateStyle: "medium",
      timeStyle: "short"
    }).format(new Date());

    const documentDefinition = buildPdfDefinition({
      pdfText,
      pdfIsArabic,
      preferredFont,
      fallbackFont,
      logoBase64,
      generatedAt,
      contentNodes
    });

    return new Promise((resolve, reject) => {
      try {
        pdfMake.createPdf(documentDefinition).download("Nabta_AI_Report.pdf");
        resolve();
      } catch (primaryError) {
        try {
          if (!fallbackFont) {
            throw primaryError;
          }

          const fallbackOptions = {
            ...normalizationOptions,
            preferredFont: fallbackFont,
            fallbackFont: preferredFont
          };

          const fallbackContentNodes = pdfIsArabic
            ? fixBulletNodes(
                Array.isArray(convertedNodes) ? convertedNodes : [convertedNodes],
                fallbackOptions
              )
            : (Array.isArray(convertedNodes) ? convertedNodes : [convertedNodes]);

          const fallbackDefinition = buildPdfDefinition({
            pdfText,
            pdfIsArabic,
            preferredFont: fallbackFont,
            fallbackFont: preferredFont,
            logoBase64,
            generatedAt,
            contentNodes: fallbackContentNodes
          });

          pdfMake.createPdf(fallbackDefinition).download("Nabta_AI_Report.pdf");
          resolve();
        } catch (fallbackError) {
          reject(fallbackError || primaryError);
        }
      }
    });
  };

  const handleDownloadWithProgress = async (msgId, originalText, reportLanguage) => {
    setDownloadingId(msgId);
    setDownloadProgress(0);
    
    // Simulate progress while PDF is being generated
    const progressInterval = setInterval(() => {
      setDownloadProgress(prev => {
        if (prev >= 90) return prev;
        return prev + 10;
      });
    }, 100);
    
    try {
      await downloadPdf(originalText, reportLanguage);
      setDownloadProgress(100);
      setTimeout(() => {
        setDownloadingId(null);
        setDownloadProgress(0);
      }, 500);
    } catch (err) {
      console.error(err);
      setDownloadingId(null);
      setDownloadProgress(0);
    } finally {
      clearInterval(progressInterval);
    }
  };

  useEffect(() => {
    const unsub = onAuthStateChanged(auth, (user) => {
      setAuthUser(user || null);
      if (!user) {
        setChatSessions([]);
        setActiveChatId("");
        setMessages([]);
        setChatSessionsError("");
      }
    });

    return () => unsub();
  }, []);

  useEffect(() => {
    const handleOutsideClick = (event) => {
      if (!sessionsPanelRef.current?.contains(event.target)) {
        setOpenSessionMenuId("");
      }
    };

    document.addEventListener("mousedown", handleOutsideClick);
    return () => document.removeEventListener("mousedown", handleOutsideClick);
  }, []);

  useEffect(() => {
    if (isSessionsCollapsed) {
      setOpenSessionMenuId("");
    }
  }, [isSessionsCollapsed]);

  useEffect(() => {
    if (!authUser?.uid) {
      return () => {};
    }

    setIsChatSessionsLoading(true);
    setChatSessionsError("");
    const sessionsRef = collection(db, "chatAi");
    const sessionsQuery = query(
      sessionsRef,
      where("ownerId", "==", authUser.uid),
      orderBy("updatedAt", "desc"),
      limit(100)
    );

    const applySessionsSnapshot = async (snapshot) => {
      const sessionItems = snapshot.docs
        .map((snap) => ({ id: snap.id, ...snap.data() }))
        .sort((a, b) => getSessionTimeValue(b) - getSessionTimeValue(a));

      setChatSessions(sessionItems);
      setIsChatSessionsLoading(false);

      if (!sessionItems.length) {
        setActiveChatId("");
        return;
      }

      setActiveChatId((prev) => {
        if (prev && sessionItems.some((session) => session.id === prev)) {
          return prev;
        }
        return sessionItems[0].id;
      });
      setOpenSessionMenuId("");
    };

    let fallbackUnsub = null;

    const handlePrimaryError = (error) => {
      console.warn("Primary chat sessions query failed, falling back:", error);
      setChatSessionsError(error?.message || "query-failed");

      const fallbackQuery = query(
        sessionsRef,
        where("ownerId", "==", authUser.uid),
        limit(100)
      );

      fallbackUnsub = onSnapshot(
        fallbackQuery,
        (fallbackSnapshot) => {
          setChatSessionsError("");
          applySessionsSnapshot(fallbackSnapshot);
        },
        (fallbackError) => {
          console.error("Fallback chat sessions query failed:", fallbackError);
          setIsChatSessionsLoading(false);
          setChatSessionsError(fallbackError?.message || "fallback-query-failed");
        }
      );
    };

    const unsub = onSnapshot(sessionsQuery, applySessionsSnapshot, handlePrimaryError);

    return () => {
      unsub();
      if (fallbackUnsub) {
        fallbackUnsub();
      }
    };
  }, [authUser?.uid]);

  useEffect(() => {
    if (!authUser?.uid || !activeChatId) {
      setMessages([]);
      return () => {};
    }

    const messagesRef = collection(db, "chatAi", activeChatId, "messages");
    const messagesQuery = query(messagesRef, orderBy("createdAt", "asc"));

    const unsub = onSnapshot(messagesQuery, (snapshot) => {
      const nextMessages = snapshot.docs.map((snap) => ({
        id: snap.id,
        ...snap.data()
      }));
      setMessages(nextMessages);
    });

    return () => unsub();
  }, [authUser?.uid, activeChatId]);

  useEffect(() => {
    scrollToBottom();
  }, [messages, loading, typedText, activeChatId]);

  useEffect(() => {
    setActiveSearchMatchIndex(0);
  }, [normalizedSearchQuery, activeChatId]);

  useEffect(() => {
    const matchElements = messagesContainerRef.current
      ? Array.from(messagesContainerRef.current.querySelectorAll(".chat-search-highlight"))
      : [];

    if (!normalizedSearchQuery || matchElements.length === 0) {
      if (typeof onSearchMatchStatsChange === "function") {
        onSearchMatchStatsChange({ current: 0, total: 0 });
      }
      return;
    }

    const boundedIndex = Math.min(activeSearchMatchIndex, matchElements.length - 1);
    if (boundedIndex !== activeSearchMatchIndex) {
      setActiveSearchMatchIndex(boundedIndex);
      return;
    }

    if (typeof onSearchMatchStatsChange === "function") {
      onSearchMatchStatsChange({ current: boundedIndex + 1, total: matchElements.length });
    }
  }, [
    filteredMessages,
    normalizedSearchQuery,
    activeSearchMatchIndex,
    typedText,
    typingMessageId,
    onSearchMatchStatsChange
  ]);

  useEffect(() => {
    if (!normalizedSearchQuery || !searchJumpRequest?.token) {
      return;
    }

    const totalMatches = messagesContainerRef.current
      ? messagesContainerRef.current.querySelectorAll(".chat-search-highlight").length
      : 0;

    if (totalMatches <= 1) {
      return;
    }

    setActiveSearchMatchIndex((prevIndex) => {
      const nextIndex = searchJumpRequest.direction === "prev"
        ? (prevIndex - 1 + totalMatches) % totalMatches
        : (prevIndex + 1) % totalMatches;

      window.requestAnimationFrame(() => {
        const targetElement = messagesContainerRef.current?.querySelector(
          `[data-search-index="${nextIndex}"]`
        );

        targetElement?.scrollIntoView({ behavior: "smooth", block: "center" });
      });

      return nextIndex;
    });
  }, [searchJumpRequest, normalizedSearchQuery]);

  useEffect(() => {
    const timer = setTimeout(() => {
      messagesEndRef.current?.scrollIntoView({ behavior: "auto" });
    }, 200);
    return () => clearTimeout(timer);
  }, [activeChatId]);

  // Typing animation effect
  useEffect(() => {
    if (!typingMessageId) return;
    const msg = messages.find(m => m.id === typingMessageId);
    if (!msg) {
      setTypingMessageId(null);
      setTypedText("");
      return;
    }

    const fullText = msg.text;
    if (typedText.length >= fullText.length) {
      setTypingMessageId(null);
      setTypedText("");
      return;
    }

    // Type word by word - speed based on message length
    const words = fullText.split(/(?<=\s)/);
    const typedWords = typedText.split(/(?<=\s)/);
    const nextWordIndex = typedWords.length;
    
    if (nextWordIndex >= words.length) {
      setTypingMessageId(null);
      setTypedText("");
      return;
    }

    // Dynamic speed: more words per tick for longer messages
    // Short (<100 words): 1 word at a time, 20ms
    // Medium (100-500 words): 2-3 words at a time, 15ms
    // Long (>500 words): 5-10 words at a time, 10ms
    let wordsPerTick = 1;
    let delay = 20;
    
    if (words.length > 500) {
      wordsPerTick = Math.ceil(words.length / 100); // finish in ~100 ticks
      delay = 5;
    } else if (words.length > 200) {
      wordsPerTick = 3;
      delay = 10;
    } else if (words.length > 100) {
      wordsPerTick = 2;
      delay = 15;
    }

    const timer = setTimeout(() => {
      const newIndex = Math.min(nextWordIndex + wordsPerTick, words.length);
      setTypedText(words.slice(0, newIndex).join(""));
    }, delay);

    return () => clearTimeout(timer);
  }, [typingMessageId, typedText, messages]);

  useEffect(() => {
    const footer = document.querySelector(".footer");
    if (footer) footer.style.display = "none";
    return () => {
      if (footer) footer.style.display = "";
    };
  }, []);

  // Auto-send pending report when available
  useEffect(() => {
    if (pendingReport && !hasProcessedReportRef.current && !loading) {
      hasProcessedReportRef.current = true;
      const { prompt, isHidden } = pendingReport;
      
      if (isHidden) {
        // Send hidden prompt (don't show as user message)
        handleSendHidden(prompt, true);
      } else {
        // Normal flow: show message in chat
        setInput(prompt);
        setTimeout(() => {
          handleSend(prompt, true);
        }, 0);
      }
    }
  }, [pendingReport, loading]);

  // Listen for new chat trigger from navbar
  useEffect(() => {
    if (newChatTrigger > 0) {
      startNewChatDraft();
      hasProcessedReportRef.current = false;
    }
  }, [newChatTrigger, authUser?.uid]);

  const autoResize = () => {
    const el = textareaRef.current;
    if (!el) return;
    el.style.height = "auto";
    el.style.height = el.scrollHeight + "px";
  };

  const detectPromptLanguage = (promptValue) => {
    if (typeof promptValue === "string") {
      return isArabic(promptValue) ? "ar" : "en";
    }

    if (promptValue?.isBatch && Array.isArray(promptValue.prompts)) {
      return promptValue.prompts.some((entry) => typeof entry === "string" && isArabic(entry))
        ? "ar"
        : "en";
    }

    return "en";
  };

  const handleSend = async (messageText = null, isReport = false) => {
    const textToSend = messageText !== null ? messageText : input;
    if (!textToSend.trim()) return;
    if (!authUser?.uid) return;
    const requestLanguage = isArabic(textToSend) ? "ar" : "en";
    setIsSessionsCollapsed(true);

    const resolvedChatId = activeChatId || await createChatSessionDocument();
    if (!resolvedChatId) {
      return;
    }

    const userMessage = {
      id: Date.now(),
      role: "user",
      text: textToSend
    };

    // Build chat history for Cohere (exclude download links)
    const chatHistory = messages
      .filter(m => !m.isDownloadLink)
      .map(m => ({
        role: m.role === "user" ? "USER" : "CHATBOT",
        message: m.text
      }));

    setMessages(prev => [...prev, userMessage]);
    if (messageText === null) {
      setInput("");
    }
    setActiveRequestLanguage(requestLanguage);
    setLoading(true);

    try {
      const activeSession = chatSessions.find((session) => session.id === resolvedChatId);
      const shouldUseMessageAsTitle = !activeSession || !activeSession.title || activeSession.title === t.untitledChat;
      await saveMessageToChat(resolvedChatId, userMessage, { useMessageAsTitle: shouldUseMessageAsTitle });

      const result = await cohereChat({
        message: textToSend,
        preamble: SYSTEM_PREAMBLE,
        chat_history: chatHistory,
        temperature: 0.3
      });

      const botMsgId = Date.now() + 1;
      const botMsg = {
        id: botMsgId,
        role: "bot",
        text: result.data.text,
        isReport
      };
      setMessages(prev => [...prev, botMsg]);
      await saveMessageToChat(resolvedChatId, botMsg);
      setTypingMessageId(botMsgId);
      setTypedText("");

      // if this was a report response, show download link
      if (isReport) {
        const reportLanguage = isArabic(result.data.text) ? "ar" : "en";
        const reportText = text[reportLanguage] || text.en;
        setMessages(prev => [...prev, {
          id: Date.now() + 2,
          role: "bot",
          text: reportText.downloadReport,
          isDownloadLink: true,
          originalText: result.data.text,
          reportLanguage,
          downloadLabel: reportText.downloadReport,
          downloadingLabel: reportText.downloading
        }]);
      }

      // Notify parent that report has been processed
      if (onReportProcessed) {
        hasProcessedReportRef.current = false;
        onReportProcessed();
      }

    } catch (err) {
      console.error(err);
      // Reset ref so we can try again
      hasProcessedReportRef.current = false;
    }

    setLoading(false);
    setActiveRequestLanguage(null);
  };

  const handleSendHidden = async (prompt) => {
    // Don't show user message, just show loading state
    const requestLanguage = detectPromptLanguage(prompt);
    if (!authUser?.uid) return;
    setIsSessionsCollapsed(true);

    const resolvedChatId = activeChatId || await createChatSessionDocument();
    if (!resolvedChatId) {
      return;
    }

    setActiveRequestLanguage(requestLanguage);
    setLoading(true);
    setIsReportLoading(true);

    try {
      let combinedText = "";

      // Check if it's a batch request
      if (prompt && prompt.isBatch && Array.isArray(prompt.prompts)) {
        // Run all batch prompts in parallel
        const results = await Promise.all(
          prompt.prompts.map(p => 
            cohereChat({
              message: p,
              preamble: SYSTEM_PREAMBLE,
              temperature: 0.3
            })
          )
        );
        // Combine all responses
        combinedText = results.map(r => r.data.text).join("\n\n---\n\n");
      } else {
        // Single prompt
        const result = await cohereChat({
          message: prompt,
          preamble: SYSTEM_PREAMBLE,
          temperature: 0.3
        });
        combinedText = result.data.text;
      }

      const hiddenBotMsgId = Date.now();
      setMessages(prev => [...prev, {
        id: hiddenBotMsgId,
        role: "bot",
        text: combinedText,
        isReport: true
      }]);
      const reportLanguage = isArabic(combinedText) ? "ar" : "en";
      await saveMessageToChat(resolvedChatId, {
        role: "bot",
        text: combinedText,
        isReport: true,
        isArabic: reportLanguage === "ar"
      });
      setTypingMessageId(hiddenBotMsgId);
      setTypedText("");

      const reportText = text[reportLanguage] || text.en;
      setMessages(prev => [...prev, {
        id: Date.now() + 1,
        role: "bot",
        text: reportText.downloadReport,
        isDownloadLink: true,
        originalText: combinedText,
        reportLanguage,
        downloadLabel: reportText.downloadReport,
        downloadingLabel: reportText.downloading
      }]);
      // Notify parent that report has been processed
      if (onReportProcessed) {
        hasProcessedReportRef.current = false;
        onReportProcessed();
      }

    } catch (err) {
      console.error(err);
      // Reset ref so we can try again
      hasProcessedReportRef.current = false;
    }

    setLoading(false);
    setIsReportLoading(false);
    setActiveRequestLanguage(null);
  };

  const handleKeyDown = (e) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend(null);
    }
  };

  const searchHighlightCounter = { value: 0 };

  return (
    <div
      className={`chat-container ${isSessionsCollapsed ? "sessions-collapsed" : ""}`}
      dir={language === "ar" ? "rtl" : "ltr"}
    >
      {isSessionsCollapsed && (
        <button
          type="button"
          className="chat-floating-toggle"
          onClick={() => setIsSessionsCollapsed(false)}
          title={t.expandChats}
        >
          <img
            src={languageSidebarIcon}
            alt="sidebar toggle"
            className={`chat-floating-toggle-icon ${isSessionsCollapsed ? "is-collapsed" : "is-expanded"}`}
          />
        </button>
      )}

      <aside className="chat-sessions-panel" ref={sessionsPanelRef}>
        <div className="chat-sessions-header">
          <h4>{t.chats}</h4>
          <div className="chat-sessions-actions">
            <button
              type="button"
              className="chat-sessions-toggle-btn"
              onClick={() => setIsSessionsCollapsed((prev) => !prev)}
              title={isSessionsCollapsed ? t.expandChats : t.collapseChats}
            >
              <img
                src={languageSidebarIcon}
                alt="sidebar toggle"
                className={`chat-sessions-toggle-icon ${isSessionsCollapsed ? "is-collapsed" : "is-expanded"}`}
              />
            </button>
            <button
              type="button"
              className="chat-sessions-new-btn"
              onClick={startNewChatDraft}
              title={t.newChatSidebar}
            >
              +
            </button>
          </div>
        </div>

        <div className="chat-sessions-list">
          {isChatSessionsLoading && <p className="chat-sessions-empty">{t.loadingChats}</p>}
          {!isChatSessionsLoading && !!chatSessionsError && (
            <p className="chat-sessions-empty">{t.chatsLoadError}</p>
          )}
          {!isChatSessionsLoading && chatSessions.length === 0 && (
            <p className="chat-sessions-empty">{t.noChats}</p>
          )}
          {chatSessions.map((session) => (
            <div
              key={session.id}
              className={`chat-session-item ${session.id === activeChatId ? "active" : ""}`}
              title={session.title || t.untitledChat}
            >
              <button
                type="button"
                className="chat-session-main-btn"
                onClick={() => {
                  setActiveChatId(session.id);
                  setInput("");
                  setOpenSessionMenuId("");
                }}
              >
                <span className="chat-session-title">{session.title || t.untitledChat}</span>
              </button>

              <div className="chat-session-menu-wrap">
                <button
                  type="button"
                  className="chat-session-menu-btn"
                  title={t.menuLabel}
                  onClick={(e) => {
                    e.stopPropagation();
                    setOpenSessionMenuId((prev) => (prev === session.id ? "" : session.id));
                  }}
                >
                  <span className="chat-session-menu-icon" aria-hidden="true">
                    <span className="chat-session-menu-dot" />
                    <span className="chat-session-menu-dot" />
                    <span className="chat-session-menu-dot" />
                  </span>
                </button>

                {openSessionMenuId === session.id && (
                  <div className="chat-session-menu" role="menu">
                    <button
                      type="button"
                      className="chat-session-menu-delete"
                      onClick={async (e) => {
                        e.stopPropagation();
                        setOpenSessionMenuId("");
                        setPendingDeleteChatId(session.id);
                      }}
                    >
                      {t.deleteChat}
                    </button>
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      </aside>

      <div className="chat-main-pane">

      <div className="chat-messages" ref={messagesContainerRef}>

        {filteredMessages.map(msg => {
          const arabic = msg.isArabic !== undefined ? msg.isArabic : isArabic(msg.text);
          const alignment = msg.role === "user"
            ? "flex-end"
            : (arabic ? "rtl-align" : "ltr-align");

          // special case for download link entries - hide while typing is in progress
          if (msg.isDownloadLink) {
            // Don't show download link while bot is still typing
            if (typingMessageId) return null;

            const isDownloading = downloadingId === msg.id;
            const downloadLabel = msg.downloadLabel || t.downloadReport;
            const downloadingLabel = msg.downloadingLabel || t.downloading;
            const labelLanguage = isArabic(downloadLabel) ? "ar" : "en";
            const reportLanguage = msg.reportLanguage
              || labelLanguage
              || (isArabic(msg.originalText || msg.text) ? "ar" : "en");
            const downloadRowAlignment = reportLanguage === "ar" ? "rtl-align" : "ltr-align";
            const downloadDir = reportLanguage === "ar" ? "rtl" : "ltr";
            return (
              <div key={msg.id} className={`chat-row ${downloadRowAlignment}`} dir={downloadDir}>
                <div className="download-pdf-link">
                  <a
                    href="#"
                    onClick={(e) => {
                      e.preventDefault();
                      if (!isDownloading) {
                        handleDownloadWithProgress(msg.id, msg.originalText, msg.reportLanguage);
                      }
                    }}
                    style={{ pointerEvents: isDownloading ? 'none' : 'auto' }}
                  >
                    {isDownloading 
                      ? `⏳ ${downloadingLabel} ${downloadProgress}%`
                      : `📄 ${downloadLabel}`
                    }
                  </a>
                </div>
              </div>
            );
          }

          const displayText = (typingMessageId === msg.id && msg.role === "bot")
            ? typedText
            : msg.text;

          return (
            <div key={msg.id} className={`chat-row ${alignment}`}>
              <div
                className={`chat-bubble ${msg.role === "user" ? "user" : "bot"}`}
                dir={arabic ? "rtl" : "ltr"}
                dangerouslySetInnerHTML={{
                  __html: highlightHtmlMatches(marked.parse(displayText || " "), normalizedSearchQuery, {
                    activeIndex: activeSearchMatchIndex,
                    counterRef: searchHighlightCounter
                  })
                }}
              />
              {typingMessageId === msg.id && (
                <span className="typing-cursor">▌</span>
              )}
            </div>
          );
        })}

        {!loading && normalizedSearchQuery && filteredMessages.length === 0 && (
          <div className="chat-search-empty" dir={language === "ar" ? "rtl" : "ltr"}>
            {t.noResults}
          </div>
        )}

        {loading && !typingMessageId && (() => {
          const lastUserMessage = messages.filter(m => m.role === "user").pop();
          const inferredLoadingLanguage = activeRequestLanguage || (
            !isReportLoading && lastUserMessage && lastUserMessage.text && isArabic(lastUserMessage.text)
              ? "ar"
              : "en"
          );
          const loadingText = inferredLoadingLanguage === "ar" ? text.ar.loading : text.en.loading;
          const loadingDir = inferredLoadingLanguage === "ar" ? "rtl" : "ltr";
          const loadingAlignment = inferredLoadingLanguage === "ar" ? "rtl-align" : "ltr-align";

          return (
            <div className={`chat-row ${loadingAlignment}`}>
              <div className="loading-bubble" dir={loadingDir}>
                <svg className="loading-sprout-svg" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M7 20h10"/>
                  <path d="M10 20c5.5-2.5.8-6.4 3-10"/>
                  <path d="M9.5 9.4c1.1.8 1.8 2.2 2.3 3.7-2 .4-3.2.4-4.8-.4-1.2-.6-2.1-1.9-2.1-3.3 0-1.9 3-3 4.6-3Z"/>
                  <path d="M14.1 6a7 7 0 0 0-1.1 4c1.9-.1 3.3-.6 4.3-1.4 1-.8 1.6-1.7 1.6-2.6 0-2.6-4.8-2.6-4.8 0Z"/>
                </svg>
                <span className="loading-text">{loadingText}</span>
              </div>
            </div>
          );
        })()}

        <div ref={messagesEndRef} />
      </div>

      <div className="chat-input-area">
        <div className="chat-input-area-inner">

          <textarea
            ref={textareaRef}
            className="chat-textarea"
            placeholder={t.placeholder}
            value={input}
            onChange={(e) => {
              setInput(e.target.value);
              setIsSessionsCollapsed(true);
              autoResize();
            }}
            onKeyDown={handleKeyDown}
          />

          <button
            className="send-btn"
            onClick={() => handleSend(null)}
            disabled={loading}
          >
            <svg viewBox="0 0 24 24">
              <path d="M3 12L21 3L14 21L11 13L3 12Z"/>
            </svg>
          </button>

        </div>

        <div className="chat-disclaimer">
          {t.disclaimer}
        </div>
      </div>

      </div>

      {pendingDeleteChatId && (
        <div className="chat-delete-modal-overlay" onClick={() => setPendingDeleteChatId("") }>
          <div
            className="chat-delete-modal"
            role="dialog"
            aria-modal="true"
            aria-labelledby="chat-delete-modal-title"
            onClick={(event) => event.stopPropagation()}
          >
            <h3 id="chat-delete-modal-title">{t.deleteChatTitle}</h3>
            <p>{t.deleteChatConfirm}</p>
            <div className="chat-delete-modal-actions">
              <button
                type="button"
                className="chat-delete-cancel-btn"
                onClick={() => setPendingDeleteChatId("")}
              >
                {t.cancelDelete}
              </button>
              <button
                type="button"
                className="chat-delete-confirm-btn"
                onClick={handleConfirmDeleteChat}
              >
                {t.confirmDelete}
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
